version: "3.9"

services:
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 5
    ports:
      - '3306:3306'
    expose:
      - '3306'
    # volumes:
    #   - mysql_vol:/var/lib/mysql

  reports-api:
    depends_on:
      mysql:
        condition: service_healthy
    build:
      context: ./reports-api/.
      dockerfile: Dockerfile
    image: reports-api:latest
    environment:
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      PORT: ${PORT}
      ENV: ${ENV}
    ports:
      - ${PORT}:${PORT}
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: "5"   # number of files or file count
        max-size: "10m" # file size

# volumes:
#   mysql_vol: