"""Added end_date not null on report table

Revision ID: 463d0c84b429
Revises: 2e7ab6e06a41
Create Date: 2023-08-25 16:45:21.494957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '463d0c84b429'
down_revision: Union[str, None] = '2e7ab6e06a41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('report', 'end_date',
               existing_type=mysql.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('report', 'end_date',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###
