"""Added report_file table

Revision ID: 9f50b93cd901
Revises: e43cb4242227
Create Date: 2023-08-28 11:59:16.555090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9f50b93cd901'
down_revision: Union[str, None] = 'e43cb4242227'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_file',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('format', sa.String(length=5), nullable=False),
    sa.Column('binary', sa.BLOB(), nullable=True),
    sa.Column('size', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('report', 'binary')
    op.drop_column('report', 'format')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report', sa.Column('format', mysql.VARCHAR(length=5), nullable=False))
    op.add_column('report', sa.Column('binary', sa.BLOB(), nullable=True))
    op.drop_table('report_file')
    # ### end Alembic commands ###
