"""Added blob to  report table

Revision ID: c67ee72c7e67
Revises: 463d0c84b429
Create Date: 2023-08-26 20:07:51.505564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c67ee72c7e67'
down_revision: Union[str, None] = '463d0c84b429'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report', sa.Column('binary', sa.BLOB(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('report', 'binary')
    # ### end Alembic commands ###
