"""Added finish_at to report table

Revision ID: e43cb4242227
Revises: c67ee72c7e67
Create Date: 2023-08-26 20:35:35.798457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e43cb4242227'
down_revision: Union[str, None] = 'c67ee72c7e67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report', sa.Column('finish_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('report', 'finish_at')
    # ### end Alembic commands ###
