"""Added format column to report table

Revision ID: ec0ea32fb2c8
Revises: 507ae2c70ddf
Create Date: 2023-08-25 16:13:56.602277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec0ea32fb2c8'
down_revision: Union[str, None] = '507ae2c70ddf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report', sa.Column('format', sa.String(length=5), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('report', 'format')
    # ### end Alembic commands ###
